In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
data = np.loadtxt("data.csv", delimiter=";", dtype=int)
years = data[:, 0]
population = data[:, 1]

In [7]:
degrees = np.arange(0, 7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
def S(x, k):
    return np.sum(x**k)

In [11]:
def T(x, y, k):
    return np.sum(x**k * y)

In [15]:
for m in degrees:
    A = []
    y = []
    for n in range(m+1):
        tmp = []
        y.append(T(years, population, n))
        for k in range(n, m+n+1):
            tmp.append(S(years, k))
        A.append(tmp)
    A = np.matrix(A)
    y = np.array(y)
    c = np.linalg.inv(A.T@A)@A.T@y

[[1.43369177e+08]]
[[-3.50101274e+09  1.87771330e+06]]
[[-1.68002258e+12  1.09301029e+12 -3.50264433e+11]]
[[-6.26808732e+17  2.16050574e+17 -1.21512541e+18 -1.24351377e+18]]
[[ 3.16914564e+19 -6.59289640e+19 -4.66723963e+18 -4.46745870e+19
  -1.78264763e+18]]
[[-4.86475160e+19 -3.26508775e+19 -4.70636002e+19 -2.70409302e+19
  -6.53079029e+18  6.63626147e+18]]
[[ 4.48501837e+19  1.14582383e+20  1.74980201e+20  1.29484770e+20
   1.75672989e+20 -2.15211227e+20 -6.64844837e+19]]
